import "./globals.css";
import 'aos/dist/aos.css';
import { Montserrat ,Red_Hat_Display} from 'next/font/google'


const inter = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-Montserrat',
})

const red_hat = Red_Hat_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-red-hat-display',
})

export const metadata = {
  title: "VINCENT",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={` ${red_hat.variable}`}>
      <head>
      <link rel="icon" href="/svg/logo.svg" sizes="any" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      </head>
      <body >
        {children}
      </body>
    </html>
  );
}
